# Generated by Django 4.1.1 on 2022-10-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comentarios", "0001_initial"),
        ("core", "0003_pontoturistico_atracoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="comentarios",
            field=models.ManyToManyField(to="comentarios.comentario"),
        ),
    ]
