# Generated by Django 4.1.1 on 2022-10-23 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("endereco", "0001_initial"),
        ("core", "0005_pontoturistico_avaliacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="endereco",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="endereco.endereco",
            ),
            preserve_default=False,
        ),
    ]
